[project]
name = "mbp-docs2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rst2pdf>=0.103.1",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
